commit before pulling 2 A6000fter

diff --git a/completeScriptP3GPU b/completeScriptP3GPU
--- a/completeScriptP3GPU
+++ b/completeScriptP3GPU
@@ -60,10 +60,26 @@ nvidia-smi
 pip install tqdm numpy matplotlib pandas scikit-learn pynvml sentencepiece transformers protobuf google
 pip install reformer-pytorch
 pip install --upgrade huggingface_hub
-nvcc --version
 python -c "import torch; print(torch.__version__); print(torch.cuda.is_available()); print(torch.version.cuda); print(torch.backends.cudnn.version())"
 python -c "import torch; print(torch.cuda.device_count())"
+nvidia-smi
+pip install tqdm numpy matplotlib pandas scikit-learn pynvml sentencepiece transformers protobuf google
+pip install reformer-pytorch
+pip install --upgrade huggingface_hub
 
+# Step 10: Run ddpTorch.sh
+SCRIPT_NAME="runScript.sh"
+if [ -f "$SCRIPT_NAME" ]; then
+    log "Running $SCRIPT_NAME..."
+    chmod +x $SCRIPT_NAME
+    ./$SCRIPT_NAME
+    #python patchtst_pretrain.py --dset custom --mask_ratio 0.4
+else
+    echo "Error: $SCRIPT_NAME not found in the current directory."
+    exit 1
+fi
+
+log "Setup process complete!"
 # Step 10: Run ddpTorch.sh
 SCRIPT_NAME="runScript3.sh"
 if [ -f "$SCRIPT_NAME" ]; then
